// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/u/:username": {
    params: {
      "username": string;
    };
  };
  "/stories/:storyId": {
    params: {
      "storyId": string;
    };
  };
  "/about": {
    params: {};
  };
  "/guidelines": {
    params: {};
  };
  "/help": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/data-deletion": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/accessibility": {
    params: {};
  };
  "/stories-of-hope": {
    params: {};
  };
  "/gratitude-stories": {
    params: {};
  };
  "/overcoming-adversity": {
    params: {};
  };
  "/stories-of-transformation": {
    params: {};
  };
  "/inspirational-testimonies": {
    params: {};
  };
  "/personal-growth-stories": {
    params: {};
  };
  "/healing-and-resilience": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/dashboard": {
    params: {};
  };
  "/notifications": {
    params: {};
  };
  "/messages": {
    params: {};
  };
  "/moderation/reports": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/profile/settings": {
    params: {};
  };
  "/profile/edit": {
    params: {};
  };
  "/security/auth-audit": {
    params: {};
  };
  "/discover": {
    params: {};
  };
  "/stories/new": {
    params: {};
  };
  "/stories/:storyId/edit": {
    params: {
      "storyId": string;
    };
  };
  "/journeys": {
    params: {};
  };
  "/journeys/:slug": {
    params: {
      "slug": string;
    };
  };
  "/aspirations": {
    params: {};
  };
  "/aspirations/new": {
    params: {};
  };
  "/aspirations/:id": {
    params: {
      "id": string;
    };
  };
  "/aspirations/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/community": {
    params: {};
  };
  "/oauth/callback": {
    params: {};
  };
  "/oauth/:provider": {
    params: {
      "provider": string;
    };
  };
  "/api/health": {
    params: {};
  };
  "/api/ai/story-suggestion": {
    params: {};
  };
  "/api/admin/email-verification-retry-health": {
    params: {};
  };
  "/auth/verify-email": {
    params: {};
  };
  "/verify-email": {
    params: {};
  };
  "/auth/mfa": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/onboarding/profile": {
    params: {};
  };
  "/onboarding/interests": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/u/:username" | "/stories/:storyId" | "/about" | "/guidelines" | "/help" | "/privacy" | "/data-deletion" | "/terms" | "/accessibility" | "/stories-of-hope" | "/gratitude-stories" | "/overcoming-adversity" | "/stories-of-transformation" | "/inspirational-testimonies" | "/personal-growth-stories" | "/healing-and-resilience" | "/*" | "/dashboard" | "/notifications" | "/messages" | "/moderation/reports" | "/profile" | "/profile/settings" | "/profile/edit" | "/security/auth-audit" | "/discover" | "/stories/new" | "/stories/:storyId/edit" | "/journeys" | "/journeys/:slug" | "/aspirations" | "/aspirations/new" | "/aspirations/:id" | "/aspirations/:id/edit" | "/community" | "/oauth/callback" | "/oauth/:provider" | "/api/health" | "/api/ai/story-suggestion" | "/api/admin/email-verification-retry-health" | "/auth/verify-email" | "/verify-email" | "/auth/mfa" | "/logout" | "/login" | "/signup" | "/forgot-password" | "/reset-password" | "/onboarding" | "/onboarding/profile" | "/onboarding/interests";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/u/:username" | "/stories/:storyId" | "/about" | "/guidelines" | "/help" | "/privacy" | "/data-deletion" | "/terms" | "/accessibility" | "/stories-of-hope" | "/gratitude-stories" | "/overcoming-adversity" | "/stories-of-transformation" | "/inspirational-testimonies" | "/personal-growth-stories" | "/healing-and-resilience" | "/*";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index/route";
    page: "/";
  };
  "routes/u.$username.tsx": {
    id: "routes/u.$username";
    page: "/u/:username";
  };
  "routes/stories.$storyId.tsx": {
    id: "routes/stories.$storyId";
    page: "/stories/:storyId";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/guidelines.tsx": {
    id: "routes/guidelines";
    page: "/guidelines";
  };
  "routes/help.tsx": {
    id: "routes/help";
    page: "/help";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/data-deletion.tsx": {
    id: "routes/data-deletion";
    page: "/data-deletion";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "routes/accessibility.tsx": {
    id: "routes/accessibility";
    page: "/accessibility";
  };
  "routes/stories-of-hope.tsx": {
    id: "routes/stories-of-hope";
    page: "/stories-of-hope";
  };
  "routes/gratitude-stories.tsx": {
    id: "routes/gratitude-stories";
    page: "/gratitude-stories";
  };
  "routes/overcoming-adversity.tsx": {
    id: "routes/overcoming-adversity";
    page: "/overcoming-adversity";
  };
  "routes/stories-of-transformation.tsx": {
    id: "routes/stories-of-transformation";
    page: "/stories-of-transformation";
  };
  "routes/inspirational-testimonies.tsx": {
    id: "routes/inspirational-testimonies";
    page: "/inspirational-testimonies";
  };
  "routes/personal-growth-stories.tsx": {
    id: "routes/personal-growth-stories";
    page: "/personal-growth-stories";
  };
  "routes/healing-and-resilience.tsx": {
    id: "routes/healing-and-resilience";
    page: "/healing-and-resilience";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
  "routes/authenticated-layout.tsx": {
    id: "routes/authenticated-layout";
    page: "/dashboard" | "/notifications" | "/messages" | "/moderation/reports" | "/profile" | "/profile/settings" | "/profile/edit" | "/security/auth-audit" | "/discover" | "/stories/new" | "/stories/:storyId/edit" | "/journeys" | "/journeys/:slug" | "/aspirations" | "/aspirations/new" | "/aspirations/:id" | "/aspirations/:id/edit" | "/community";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/notifications.tsx": {
    id: "routes/notifications";
    page: "/notifications";
  };
  "routes/messages.tsx": {
    id: "routes/messages";
    page: "/messages";
  };
  "routes/moderation.reports.tsx": {
    id: "routes/moderation.reports";
    page: "/moderation/reports";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/profile.edit.tsx": {
    id: "routes/profile.edit";
    page: "/profile/settings";
  };
  "routes/profile.redirect.tsx": {
    id: "routes/profile.redirect";
    page: "/profile/edit";
  };
  "routes/security.auth-audit.tsx": {
    id: "routes/security.auth-audit";
    page: "/security/auth-audit";
  };
  "routes/discover.tsx": {
    id: "routes/discover";
    page: "/discover";
  };
  "routes/stories.new.tsx": {
    id: "routes/stories.new";
    page: "/stories/new";
  };
  "routes/stories.$storyId.edit.tsx": {
    id: "routes/stories.$storyId.edit";
    page: "/stories/:storyId/edit";
  };
  "routes/journeys/index.tsx": {
    id: "routes/journeys/index";
    page: "/journeys";
  };
  "routes/journeys.$slug.tsx": {
    id: "routes/journeys.$slug";
    page: "/journeys/:slug";
  };
  "routes/aspirations/index.tsx": {
    id: "routes/aspirations/index";
    page: "/aspirations";
  };
  "routes/aspirations.new.tsx": {
    id: "routes/aspirations.new";
    page: "/aspirations/new";
  };
  "routes/aspirations.$id.tsx": {
    id: "routes/aspirations.$id";
    page: "/aspirations/:id";
  };
  "routes/aspirations.$id.edit.tsx": {
    id: "routes/aspirations.$id.edit";
    page: "/aspirations/:id/edit";
  };
  "routes/community.tsx": {
    id: "routes/community";
    page: "/community";
  };
  "routes/auth/oauth.callback.tsx": {
    id: "routes/auth/oauth.callback";
    page: "/oauth/callback";
  };
  "routes/auth/oauth.$provider.tsx": {
    id: "routes/auth/oauth.$provider";
    page: "/oauth/:provider";
  };
  "routes/api.health.ts": {
    id: "routes/api.health";
    page: "/api/health";
  };
  "routes/api.ai.story-suggestion.ts": {
    id: "routes/api.ai.story-suggestion";
    page: "/api/ai/story-suggestion";
  };
  "routes/api.admin.email-verification-retry-health.ts": {
    id: "routes/api.admin.email-verification-retry-health";
    page: "/api/admin/email-verification-retry-health";
  };
  "routes/auth/verify-email.tsx": {
    id: "routes/auth/verify-email";
    page: "/auth/verify-email";
  };
  "routes/auth/verify-email-status.tsx": {
    id: "routes/auth/verify-email-status";
    page: "/verify-email";
  };
  "routes/auth/mfa.tsx": {
    id: "routes/auth/mfa";
    page: "/auth/mfa";
  };
  "routes/auth/logout.tsx": {
    id: "routes/auth/logout";
    page: "/logout";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/login";
  };
  "routes/auth/signup.tsx": {
    id: "routes/auth/signup";
    page: "/signup";
  };
  "routes/auth/forgot-password.tsx": {
    id: "routes/auth/forgot-password";
    page: "/forgot-password";
  };
  "routes/auth/reset-password.tsx": {
    id: "routes/auth/reset-password";
    page: "/reset-password";
  };
  "routes/onboarding.layout.tsx": {
    id: "routes/onboarding.layout";
    page: "/onboarding" | "/onboarding/profile" | "/onboarding/interests";
  };
  "routes/onboarding.profile.tsx": {
    id: "routes/onboarding.profile";
    page: "/onboarding/profile";
  };
  "routes/onboarding.interests.tsx": {
    id: "routes/onboarding.interests";
    page: "/onboarding/interests";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/layout": typeof import("./app/routes/layout.tsx");
  "routes/_index/route": typeof import("./app/routes/_index/route.tsx");
  "routes/u.$username": typeof import("./app/routes/u.$username.tsx");
  "routes/stories.$storyId": typeof import("./app/routes/stories.$storyId.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/guidelines": typeof import("./app/routes/guidelines.tsx");
  "routes/help": typeof import("./app/routes/help.tsx");
  "routes/privacy": typeof import("./app/routes/privacy.tsx");
  "routes/data-deletion": typeof import("./app/routes/data-deletion.tsx");
  "routes/terms": typeof import("./app/routes/terms.tsx");
  "routes/accessibility": typeof import("./app/routes/accessibility.tsx");
  "routes/stories-of-hope": typeof import("./app/routes/stories-of-hope.tsx");
  "routes/gratitude-stories": typeof import("./app/routes/gratitude-stories.tsx");
  "routes/overcoming-adversity": typeof import("./app/routes/overcoming-adversity.tsx");
  "routes/stories-of-transformation": typeof import("./app/routes/stories-of-transformation.tsx");
  "routes/inspirational-testimonies": typeof import("./app/routes/inspirational-testimonies.tsx");
  "routes/personal-growth-stories": typeof import("./app/routes/personal-growth-stories.tsx");
  "routes/healing-and-resilience": typeof import("./app/routes/healing-and-resilience.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
  "routes/authenticated-layout": typeof import("./app/routes/authenticated-layout.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/notifications": typeof import("./app/routes/notifications.tsx");
  "routes/messages": typeof import("./app/routes/messages.tsx");
  "routes/moderation.reports": typeof import("./app/routes/moderation.reports.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/profile.edit": typeof import("./app/routes/profile.edit.tsx");
  "routes/profile.redirect": typeof import("./app/routes/profile.redirect.tsx");
  "routes/security.auth-audit": typeof import("./app/routes/security.auth-audit.tsx");
  "routes/discover": typeof import("./app/routes/discover.tsx");
  "routes/stories.new": typeof import("./app/routes/stories.new.tsx");
  "routes/stories.$storyId.edit": typeof import("./app/routes/stories.$storyId.edit.tsx");
  "routes/journeys/index": typeof import("./app/routes/journeys/index.tsx");
  "routes/journeys.$slug": typeof import("./app/routes/journeys.$slug.tsx");
  "routes/aspirations/index": typeof import("./app/routes/aspirations/index.tsx");
  "routes/aspirations.new": typeof import("./app/routes/aspirations.new.tsx");
  "routes/aspirations.$id": typeof import("./app/routes/aspirations.$id.tsx");
  "routes/aspirations.$id.edit": typeof import("./app/routes/aspirations.$id.edit.tsx");
  "routes/community": typeof import("./app/routes/community.tsx");
  "routes/auth/oauth.callback": typeof import("./app/routes/auth/oauth.callback.tsx");
  "routes/auth/oauth.$provider": typeof import("./app/routes/auth/oauth.$provider.tsx");
  "routes/api.health": typeof import("./app/routes/api.health.ts");
  "routes/api.ai.story-suggestion": typeof import("./app/routes/api.ai.story-suggestion.ts");
  "routes/api.admin.email-verification-retry-health": typeof import("./app/routes/api.admin.email-verification-retry-health.ts");
  "routes/auth/verify-email": typeof import("./app/routes/auth/verify-email.tsx");
  "routes/auth/verify-email-status": typeof import("./app/routes/auth/verify-email-status.tsx");
  "routes/auth/mfa": typeof import("./app/routes/auth/mfa.tsx");
  "routes/auth/logout": typeof import("./app/routes/auth/logout.tsx");
  "routes/auth/login": typeof import("./app/routes/auth/login.tsx");
  "routes/auth/signup": typeof import("./app/routes/auth/signup.tsx");
  "routes/auth/forgot-password": typeof import("./app/routes/auth/forgot-password.tsx");
  "routes/auth/reset-password": typeof import("./app/routes/auth/reset-password.tsx");
  "routes/onboarding.layout": typeof import("./app/routes/onboarding.layout.tsx");
  "routes/onboarding.profile": typeof import("./app/routes/onboarding.profile.tsx");
  "routes/onboarding.interests": typeof import("./app/routes/onboarding.interests.tsx");
};